

<!DOCTYPE html>
<!--[if IE 8]><html class="no-js lt-ie9" lang="en" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="en" > <!--<![endif]-->
<head>
  <meta charset="utf-8">
  
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  
  <title>2. Defensive programming &mdash; Mastering Python</title>
  

  
  
    <link rel="shortcut icon" href="../../../../_static/favicon.ico"/>
  
  
  

  
  <script type="text/javascript" src="../../../../_static/js/modernizr.min.js"></script>
  
    
      <script type="text/javascript" id="documentation_options" data-url_root="../../../../" src="../../../../_static/documentation_options.js"></script>
        <script src="../../../../_static/jquery.js"></script>
        <script src="../../../../_static/underscore.js"></script>
        <script src="../../../../_static/doctools.js"></script>
        <script src="../../../../_static/language_data.js"></script>
    
    <script type="text/javascript" src="../../../../_static/js/theme.js"></script>

    

  
  <link rel="stylesheet" href="../../../../_static/css/theme.css" type="text/css" />
  <link rel="stylesheet" href="../../../../_static/pygments.css" type="text/css" />
  <link rel="stylesheet" href="../../../../_static/styles.css" type="text/css" />
    <link rel="index" title="Index" href="../../../../genindex.html" />
    <link rel="search" title="Search" href="../../../../search.html" /> 
</head>

<body class="wy-body-for-nav">

   
  <div class="wy-grid-for-nav">
    
    <nav data-toggle="wy-nav-shift" class="wy-nav-side">
      <div class="wy-side-scroll">
        <div class="wy-side-nav-search" >
          

          
            <a href="../../../../index.html" class="icon icon-home"> Mastering Python
          

          
            
            <img src="../../../../_static/logo-white.png" class="logo" alt="Logo"/>
          
          </a>

          
            
            
              <div class="version">
                20/03/2020
              </div>
            
          

          
<div role="search">
  <form id="rtd-search-form" class="wy-form" action="../../../../search.html" method="get">
    <input type="text" name="q" placeholder="Search docs" />
    <input type="hidden" name="check_keywords" value="yes" />
    <input type="hidden" name="area" value="default" />
  </form>
</div>

          
        </div>

        <div class="wy-menu wy-menu-vertical" data-spy="affix" role="navigation" aria-label="main navigation">
          
            
            
              
            
            
              <ul>
<li class="toctree-l1"><a class="reference internal" href="../../index.html">Craftmanship</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../structures_algorithms/index.html">Data structures and algorithms</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../quality/index.html">Code quality</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../optimization/index.html">Code optimization</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../technical_architecture/index.html">Technical architecture</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../low_level/index.html">Low level Python</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../distribution/index.html">Code distribution</a></li>
<li class="toctree-l1"><a class="reference internal" href="../../../references/index.html">References</a></li>
</ul>

            
          
        </div>
      </div>
    </nav>

    <section data-toggle="wy-nav-shift" class="wy-nav-content-wrap">

      
      <nav class="wy-nav-top" aria-label="top navigation">
        
          <i data-toggle="wy-nav-top" class="fa fa-bars"></i>
          <a href="../../../../index.html">Mastering Python</a>
        
      </nav>


      <div class="wy-nav-content">
        
        <div class="rst-content">
        
          















<div role="navigation" aria-label="breadcrumbs navigation">

  <ul class="wy-breadcrumbs">
    
      <li><a href="../../../../index.html">Docs</a> &raquo;</li>
        
      <li>2. Defensive programming</li>
    
    
      <li class="wy-breadcrumbs-aside">
        
            
            <a href="../../../../_sources/parts/craftmanship/chapters/general_traits/defensive_programming.rst.txt" rel="nofollow"> View page source</a>
          
        
      </li>
    
  </ul>

  
  <hr/>
</div>
          <div role="main" class="document" itemscope="itemscope" itemtype="http://schema.org/Article">
           <div itemprop="articleBody">
            
  <div class="section" id="defensive-programming">
<h1>2. Defensive programming<a class="headerlink" href="#defensive-programming" title="Permalink to this headline">¶</a></h1>
<p>Defensive programming follows a somewhat different approach than DbC; instead of stating all conditions that
must be held in a contract, that if unmet will raise an exception and make the program fail, this is more
about making all parts of the code (objects, functions, or methods) able to protect themselves against invalid
inputs.</p>
<p>Defensive programming is a technique that has several aspects, and it is particularly useful if it is combined
with other design principles (this means that the fact that it follows a different philosophy than DbC does
not mean that it is a case of either one or the other—it could mean that they might complement each other).</p>
<p>The main ideas on the subject of defensive programming are how to handle errors for scenarios that we might
expect to occur, and how to deal with errors that should never occur (when impossible conditions happen). The
former will fall into error handling procedures, while the latter will be the case for assertions, both topics
we will be exploring in the following sections.</p>
<div class="section" id="error-handling">
<h2>2.1. Error handling<a class="headerlink" href="#error-handling" title="Permalink to this headline">¶</a></h2>
<p>In our programs, we resort to error handling procedures for situations that we anticipate as prone to cause
errors. This is usually the case for data input.</p>
<p>The idea behind error handling is to gracefully respond to these expected errors in an attempt to either
continue our program execution or decide to fail if the error turns out to be insurmountable.</p>
<p>There are different approaches by which we can handle errors on our programs, but not all of them are always
applicable. Some of these approaches are as follows:</p>
<ul class="simple">
<li><p>Value substitution</p></li>
<li><p>Error logging</p></li>
<li><p>Exception handling</p></li>
</ul>
<div class="section" id="value-substitution">
<h3>2.1.1. Value substitution<a class="headerlink" href="#value-substitution" title="Permalink to this headline">¶</a></h3>
<p>In some scenarios, when there is an error and there is a risk of the software producing an incorrect value or
failing entirely, we might be able to replace the result with another, safer value. We call this value
substitution, since we are in fact replacing the actual erroneous result for a value that is to be considered
non-disruptive (it could be a default, a well-known constant, a sentinel value, or simply something that does
not affect the result at all, like returning zero in a case where the result is intended to be applied to a
sum).</p>
<p>Value substitution is not always possible, however. This strategy has to be carefully chosen for cases where
the substituted value is actually a safe option. Making this decision is a trade-off between robustness and
correctness. A software program is robust when it does not fail, even in the presence of an erroneous
scenario. But this is not correct either. This might not be acceptable for some kinds of software. If the
application is critical, or the data being handled is too sensitive, this is not an option, since we cannot
afford to provide users (or other parts of the application) with erroneous results. In these cases, we opt
for correctness, rather than let the program explode when yielding the wrong results.</p>
<p>A slightly different, and safer, version of this decision is to use default values for data that is not
provided. This can be the case for parts of the code that can work with a default behavior, for example,
default values for environment variables that are not set, for missing entries in configuration files, or for
parameters of functions. We can find examples of Python supporting this throughout different methods of its
API, for example, dictionaries have a get method, whose (optional) second parameter allows you to indicate a
default value:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="n">configuration</span> <span class="o">=</span> <span class="p">{</span><span class="s2">&quot;dbport&quot;</span><span class="p">:</span> <span class="mi">5432</span><span class="p">}</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">configuration</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="s2">&quot;dbhost&quot;</span><span class="p">,</span> <span class="s2">&quot;localhost&quot;</span><span class="p">)</span>
<span class="go">&#39;localhost&#39;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">configuration</span><span class="o">.</span><span class="n">get</span><span class="p">(</span><span class="s2">&quot;dbport&quot;</span><span class="p">)</span>
<span class="go">5432</span>
</pre></div>
</div>
<p>Environment variables have a similar API:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="kn">import</span> <span class="nn">os</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">os</span><span class="o">.</span><span class="n">getenv</span><span class="p">(</span><span class="s2">&quot;DBHOST&quot;</span><span class="p">)</span>
<span class="go">&#39;localhost&#39;</span>
<span class="gp">&gt;&gt;&gt; </span><span class="n">os</span><span class="o">.</span><span class="n">getenv</span><span class="p">(</span><span class="s2">&quot;DPORT&quot;</span><span class="p">,</span> <span class="mi">5432</span><span class="p">)</span>
<span class="go">5432</span>
</pre></div>
</div>
<p>In both previous examples, if the second parameter is not provided, None will be returned, because it’s the
default value those functions are defined with. We can also define default values for the parameters of our
own functions:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="gp">&gt;&gt;&gt; </span><span class="k">def</span> <span class="nf">connect_database</span><span class="p">(</span><span class="n">host</span><span class="o">=</span><span class="s2">&quot;localhost&quot;</span><span class="p">,</span> <span class="n">port</span><span class="o">=</span><span class="mi">5432</span><span class="p">):</span>
<span class="gp">...</span>
<span class="go">        logger.info(&quot;connecting to database server at %s:%i&quot;, host, port)</span>
</pre></div>
</div>
<p>In general, replacing missing parameters with default values is acceptable, but substituting erroneous data
with legal close values is more dangerous and can mask some errors. Take this criterion into consideration
when deciding on this approach.</p>
</div>
<div class="section" id="exception-handling">
<h3>2.1.2. Exception handling<a class="headerlink" href="#exception-handling" title="Permalink to this headline">¶</a></h3>
<p>In the presence of incorrect or missing input data, sometimes it is possible to correct the situation with
some examples such as the ones mentioned in the previous section. In other cases, however, it is better to
stop the program from continuing to run with the wrong data than to leave it computing under erroneous
assumptions. In those cases, failing and notifying the caller that something is wrong is a good approach, and
this is the case for a precondition that was violated, as we saw in DbC.</p>
<p>Nonetheless, erroneous input data is not the only possible way in which a function can go wrong. After all,
functions are not just about passing data around; they also have side-effects and connect to external
components.</p>
<p>It could be possible that a fault in a function call is due to a problem on one of these external components,
and not in our function itself. If that is the case, our function should communicate this properly. This will
make it easier to debug. The function should clearly and unambiguously notify the rest of the application
about errors that cannot be ignored so that they can be addressed accordingly.</p>
<p>The mechanism for accomplishing this is an exception. It is important to emphasize that this is what
exceptions should be used for—clearly announcing an exceptional situation, not altering the flow of the
program according to business logic.</p>
<p>If the code tries to use exceptions to handle expected scenarios or business logic, the flow of the program
will become harder to read. This will lead to a situation where exceptions are used as a sort of go-to
statement, that (to make things worse) could span multiple levels on the call stack (up to caller functions),
violating the encapsulation of the logic into its correct level of abstraction. The case could get even worse
if these except blocks are mixing business logic with truly exceptional cases that the code is trying to
defend against; in that case, it will be harder to distinguish between the core logic we have to maintain and
errors to be handled.</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Do not use exceptions as a go-to mechanism for business logic. Raise exceptions when there is
actually something wrong with the code that callers need to be aware of.</p>
</div>
<p>This last concept is an important one; exceptions are usually about notifying the caller about something that
is amiss. This means that exceptions should be used carefully because they weaken encapsulation. The more
exceptions a function has, the more the caller function will have to anticipate, therefore knowing about the
function it is calling. And if a function raises too many exceptions, this means that is not so context-free,
because every time we want to invoke it, we will have to keep all of its possible side-effects in mind.</p>
<p>This can be used as a heuristic to tell when a function is not cohesive enough and has too many
responsibilities. If it raises too many exceptions, it could be a sign that it has to be broken down into
multiple, smaller ones.</p>
<div class="section" id="handle-exceptions-at-the-right-level-of-abstraction">
<h4>2.1.2.1. Handle exceptions at the right level of abstraction<a class="headerlink" href="#handle-exceptions-at-the-right-level-of-abstraction" title="Permalink to this headline">¶</a></h4>
<p>Exceptions are also part of the principal functions that do one thing, and one thing only. The exception the
function is handling (or raising) has to be consistent with the logic encapsulated on it.</p>
<p>In this example, we can see what we mean by mixing different levels of abstractions. Imagine an object that
acts as a transport for some data in our application. It connects to an external component where the data is
going to be sent upon decoding. In the following listing, we will focus on the deliver_event method:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">DataTransport</span><span class="p">:</span>
    <span class="sd">&quot;&quot;&quot;An example of an object handling exceptions of different levels.&quot;&quot;&quot;</span>
    <span class="n">retry_threshold</span><span class="p">:</span> <span class="nb">int</span> <span class="o">=</span> <span class="mi">5</span>
    <span class="n">retry_n_times</span><span class="p">:</span> <span class="nb">int</span> <span class="o">=</span> <span class="mi">3</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">connector</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_connector</span> <span class="o">=</span> <span class="n">connector</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">connection</span> <span class="o">=</span> <span class="kc">None</span>

    <span class="k">def</span> <span class="nf">deliver_event</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">event</span><span class="p">):</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">connect</span><span class="p">()</span>
            <span class="n">data</span> <span class="o">=</span> <span class="n">event</span><span class="o">.</span><span class="n">decode</span><span class="p">()</span>
            <span class="bp">self</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="n">data</span><span class="p">)</span>
        <span class="k">except</span> <span class="ne">ConnectionError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
            <span class="n">logger</span><span class="o">.</span><span class="n">info</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;connection error detected: </span><span class="si">{e}</span><span class="s2">&quot;</span><span class="p">)</span>
            <span class="k">raise</span>
        <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
            <span class="n">logger</span><span class="o">.</span><span class="n">error</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;</span><span class="si">{event}</span><span class="s2"> contains incorrect data: </span><span class="si">{e}</span><span class="s2">&quot;</span><span class="p">)</span>
            <span class="k">raise</span>

    <span class="k">def</span> <span class="nf">connect</span><span class="p">(</span><span class="bp">self</span><span class="p">):</span>
        <span class="k">for</span> <span class="n">_</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">retry_n_times</span><span class="p">):</span>
            <span class="k">try</span><span class="p">:</span>
                <span class="bp">self</span><span class="o">.</span><span class="n">connection</span> <span class="o">=</span> <span class="bp">self</span><span class="o">.</span><span class="n">_connector</span><span class="o">.</span><span class="n">connect</span><span class="p">()</span>
            <span class="k">except</span> <span class="ne">ConnectionError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
                <span class="n">logger</span><span class="o">.</span><span class="n">info</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;</span><span class="si">{e}</span><span class="s2">: attempting new connection in </span><span class="si">{self.retry_threshold}</span><span class="s2">&quot;</span><span class="p">)</span>
                <span class="n">time</span><span class="o">.</span><span class="n">sleep</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">retry_threshold</span><span class="p">)</span>
            <span class="k">else</span><span class="p">:</span>
                <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">connection</span>

        <span class="k">raise</span> <span class="ne">ConnectionError</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;Couldn&#39;t connect after </span><span class="si">{self.retry_n_times}</span><span class="s2"> times&quot;</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">data</span><span class="p">):</span>
            <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">connection</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="n">data</span><span class="p">)</span>
</pre></div>
</div>
<p>For our analysis, let’s zoom in and focus on how the deliver_event() method handles exceptions.</p>
<p>What does <code class="docutils literal notranslate"><span class="pre">ValueError</span></code> have to do with <code class="docutils literal notranslate"><span class="pre">ConnectionError</span></code>? Not much. By looking at these two highly
different types of error, we can get an idea of how responsibilities should be divided. The
<code class="docutils literal notranslate"><span class="pre">ConnectionError</span></code> should be handled inside the connect method. This will allow a clear separation of
behavior. For example, if this method needs to support retries, that would be a way of doing it. Conversely,
<code class="docutils literal notranslate"><span class="pre">ValueError</span></code> belongs to the decode method of the event. With this new implementation, this method does not
need to catch any exception: the exceptions it was worrying about before are either handled by internal
methods or deliberately left to be raised.</p>
<p>We should separate these fragments into different methods or functions. For connection management, a small
function should be enough. This function will be in charge of trying to establish the connection, catching
exceptions (should they occur), and logging them accordingly:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">def</span> <span class="nf">connect_with_retry</span><span class="p">(</span><span class="n">connector</span><span class="p">,</span> <span class="n">retry_n_times</span><span class="p">,</span> <span class="n">retry_threshold</span><span class="o">=</span><span class="mi">5</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;Tries to establish the connection of &lt;connector&gt; retrying</span>
<span class="sd">    &lt;retry_n_times&gt;.</span>
<span class="sd">    If it can connect, returns the connection object.</span>
<span class="sd">    If it&#39;s not possible after the retries, raises ConnectionError</span>
<span class="sd">    :param connector: An object with a `.connect()` method.</span>
<span class="sd">    :param retry_n_times int: The number of times to try to call</span>
<span class="sd">    ``connector.connect()``.</span>
<span class="sd">    :param retry_threshold int: The time lapse between retry calls.</span>
<span class="sd">    &quot;&quot;&quot;</span>
    <span class="k">for</span> <span class="n">_</span> <span class="ow">in</span> <span class="nb">range</span><span class="p">(</span><span class="n">retry_n_times</span><span class="p">):</span>
    <span class="k">try</span><span class="p">:</span>
        <span class="k">return</span> <span class="n">connector</span><span class="o">.</span><span class="n">connect</span><span class="p">()</span>
    <span class="k">except</span> <span class="ne">ConnectionError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
        <span class="n">logger</span><span class="o">.</span><span class="n">info</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;</span><span class="si">{e}</span><span class="s2">: attempting new connection in </span><span class="si">{retry_threshold}</span><span class="s2">&quot;</span><span class="p">)</span>
        <span class="n">time</span><span class="o">.</span><span class="n">sleep</span><span class="p">(</span><span class="n">retry_threshold</span><span class="p">)</span>
    <span class="n">exc</span> <span class="o">=</span> <span class="ne">ConnectionError</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;Couldn&#39;t connect after </span><span class="si">{retry_n_times}</span><span class="s2"> times&quot;</span><span class="p">)</span>
    <span class="n">logger</span><span class="o">.</span><span class="n">exception</span><span class="p">(</span><span class="n">exc</span><span class="p">)</span>
    <span class="k">raise</span> <span class="n">exc</span>
</pre></div>
</div>
<p>Then, we will call this function in our method. As for the <code class="docutils literal notranslate"><span class="pre">ValueError</span></code> exception on the event, we could
separate it with a new object and do composition, but for this limited case it would be overkill, so just
moving the logic to a separate method would be enough. With these two considerations in place, the new version
of the method looks much more compact and easier to read:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">DataTransport</span><span class="p">:</span>
    <span class="sd">&quot;&quot;&quot;An example of an object that separates the exception handling by</span>
<span class="sd">    abstraction levels.</span>
<span class="sd">    &quot;&quot;&quot;</span>
    <span class="n">retry_threshold</span><span class="p">:</span> <span class="nb">int</span> <span class="o">=</span> <span class="mi">5</span>
    <span class="n">retry_n_times</span><span class="p">:</span> <span class="nb">int</span> <span class="o">=</span> <span class="mi">3</span>

    <span class="k">def</span> <span class="fm">__init__</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">connector</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">_connector</span> <span class="o">=</span> <span class="n">connector</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">connection</span> <span class="o">=</span> <span class="kc">None</span>

    <span class="k">def</span> <span class="nf">deliver_event</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">event</span><span class="p">):</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">connection</span> <span class="o">=</span> <span class="n">connect_with_retry</span><span class="p">(</span><span class="bp">self</span><span class="o">.</span><span class="n">_connector</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">retry_n_times</span><span class="p">,</span> <span class="bp">self</span><span class="o">.</span><span class="n">retry_threshold</span><span class="p">)</span>
        <span class="bp">self</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="n">event</span><span class="p">)</span>

    <span class="k">def</span> <span class="nf">send</span><span class="p">(</span><span class="bp">self</span><span class="p">,</span> <span class="n">event</span><span class="p">):</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">return</span> <span class="bp">self</span><span class="o">.</span><span class="n">connection</span><span class="o">.</span><span class="n">send</span><span class="p">(</span><span class="n">event</span><span class="o">.</span><span class="n">decode</span><span class="p">())</span>
        <span class="k">except</span> <span class="ne">ValueError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
            <span class="n">logger</span><span class="o">.</span><span class="n">error</span><span class="p">(</span><span class="sa">f</span><span class="s2">&quot;</span><span class="si">{event}</span><span class="s2"> contains incorrect data: </span><span class="si">{e}</span><span class="s2">&quot;</span><span class="p">)</span>
            <span class="k">raise</span>
</pre></div>
</div>
</div>
<div class="section" id="do-not-expose-tracebacks">
<h4>2.1.2.2 Do not expose tracebacks<a class="headerlink" href="#do-not-expose-tracebacks" title="Permalink to this headline">¶</a></h4>
<p>This is a security consideration. When dealing with exceptions, it might be acceptable to let them propagate
if the error is too important, and maybe even let the program fail if this is the decision for that particular
scenario and correctness was favored over robustness.</p>
<p>When there is an exception that denotes a problem, it’s important to log in with as much detail as possible
(including the traceback information, message, and all we can gather) so that the issue can be corrected
efficiently. At the same time, we want to include as much detail as possible for ourselves: we definitely
don’t want any of this becoming visible to users.</p>
<p>In Python, tracebacks of exceptions contain very rich and useful debugging information. Unfortunately, this
information is also very useful for attackers or malicious users who want to try and harm the application, not
to mention that the leak would represent an important information disclosure, jeopardizing the intellectual
property of your organization (parts of the code will be exposed).</p>
<p>If you choose to let exceptions propagate, make sure not to disclose any sensitive information. Also, if you
have to notify users about a problem, choose generic messages (such as Something went wrong, or Page not
found). This is a common technique used in web applications that display generic informative messages when an
HTTP error occurs.</p>
</div>
<div class="section" id="avoid-empty-except-blocks">
<h4>2.1.2.3 Avoid empty except blocks<a class="headerlink" href="#avoid-empty-except-blocks" title="Permalink to this headline">¶</a></h4>
<p>This was even referred to as the most diabolical Python anti-pattern. While it is good to anticipate and
defend our programs against some errors, being too defensive might lead to even worse problems. In particular,
the only problem with being too defensive is that there is an empty except block that silently passes without
doing anything.</p>
<p>Python is so flexible that it allows us to write code that can be faulty and yet, will not raise an error,
like this:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="n">process_data</span><span class="p">()</span>
<span class="k">except</span><span class="p">:</span>
    <span class="k">pass</span>
</pre></div>
</div>
<p>The problem with this is that it will not fail, ever. Even when it should. It is also non-Pythonic if you
remember from the zen of Python that errors should never pass silently.</p>
<p>If there is a true exception, this block of code will not fail, which might be what we wanted in the first
place. But what if there is a defect? We need to know if there is an error in our logic to be able to correct
it. Writing blocks such as this one will mask problems, making things harder to maintain.</p>
<p>There are two alternatives:</p>
<ul class="simple">
<li><p>Catch a more specific exception (not too broad, such as an Exception). In fact, some linting tools and IDEs will warn you in some cases when the code is handling too broad an exception.</p></li>
<li><p>Do some actual error handling on the except block.</p></li>
</ul>
<p>The best thing to do would be to apply both items simultaneously.</p>
<p>Handling a more specific exception (for example, AttributeError or KeyError) will make the program more
maintainable because the reader will know what to expect, and can get an idea of the why of it. It will also
leave other exceptions free to be raised, and if that happens, this probably means a bug, only this time it
can be discovered.</p>
<p>Handling the exception itself can mean multiple things. In its simplest form, it could be just about logging
the exception (make sure to use logger.exception or logger.error to provide the full context of what
happened). Other alternatives could be to return a default value (substitution, only that in this case after
detecting an error, not prior to causing it), or raising a different exception.</p>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>If you choose to raise a different exception, to include the original exception that caused the problem,
which leads us to the next point.</p>
</div>
</div>
<div class="section" id="include-the-original-exception">
<h4>2.1.2.4. Include the original exception<a class="headerlink" href="#include-the-original-exception" title="Permalink to this headline">¶</a></h4>
<p>As part of our error handling logic, we might decide to raise a different one, and maybe even change its
message. If that is the case, it is recommended to include the original exception that led to that.</p>
<p>In Python 3, we can now use the raise &lt;e&gt; from &lt;original_exception&gt; syntax. When using this construction, the
original traceback will be embedded into the new exception, and the original exception will be set in the
<code class="docutils literal notranslate"><span class="pre">__cause__</span></code> attribute of the resulting one.</p>
<p>For example, if we desire to wrap default exceptions with custom ones internally to our project, we could
still do that while including information about the root exception:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">class</span> <span class="nc">InternalDataError</span><span class="p">(</span><span class="ne">Exception</span><span class="p">):</span>
    <span class="sd">&quot;&quot;&quot;An exception with the data of our domain problem.&quot;&quot;&quot;</span>
    <span class="k">def</span> <span class="nf">process</span><span class="p">(</span><span class="n">data_dictionary</span><span class="p">,</span> <span class="n">record_id</span><span class="p">):</span>
        <span class="k">try</span><span class="p">:</span>
            <span class="k">return</span> <span class="n">data_dictionary</span><span class="p">[</span><span class="n">record_id</span><span class="p">]</span>
        <span class="k">except</span> <span class="ne">KeyError</span> <span class="k">as</span> <span class="n">e</span><span class="p">:</span>
            <span class="k">raise</span> <span class="n">InternalDataError</span><span class="p">(</span><span class="s2">&quot;Record not present&quot;</span><span class="p">)</span> <span class="kn">from</span> <span class="nn">e</span>
</pre></div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Always use the raise &lt;e&gt; from &lt;o&gt; syntax when changing the type of the exception.</p>
</div>
</div>
</div>
</div>
<div class="section" id="using-assertions-in-python">
<h2>2.2. Using assertions in Python<a class="headerlink" href="#using-assertions-in-python" title="Permalink to this headline">¶</a></h2>
<p>Assertions are to be used for situations that should never happen, so the expression on the assert statement
has to mean an impossible condition. Should this condition happen, it means there is a defect in the software.</p>
<p>In contrast with the error handling approach, here there is (or should not be) a possibility of continuing the
program. If such an error occurs, the program must stop. It makes sense to stop the program because, as
commented before, we are in the presence of a defect, so there is no way to move forward by releasing a new
version of the software that corrects this defect.</p>
<p>The idea of using assertions is to prevent the program from causing further damage if such an invalid scenario
is presented. Sometimes, it is better to stop and let the program crash, rather than let it continue
processing under the wrong assumptions.</p>
<p>For this reason, assertions should not be mixed with the business logic, or used as control flow mechanisms
for the software. The following example is a bad idea:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="k">try</span><span class="p">:</span>
    <span class="k">assert</span> <span class="n">condition</span><span class="o">.</span><span class="n">holds</span><span class="p">(),</span> <span class="s2">&quot;Condition is not satisfied&quot;</span>
<span class="k">except</span> <span class="ne">AssertionError</span><span class="p">:</span>
    <span class="n">alternative_procedure</span><span class="p">()</span>
</pre></div>
</div>
<div class="admonition note">
<p class="admonition-title">Note</p>
<p>Do not catch the AssertionError exception.</p>
</div>
<p>Make sure that the program terminates when an assertion fails.</p>
<p>Include a descriptive error message in the assertion statement and log the errors to make sure that you can
properly debug and correct the problem later on.</p>
<p>Another important reason why the previous code is a bad idea is that besides catching AssertionError, the
statement in the assertion is a function call. Function calls can have side-effects, and they aren’t always
repeatable (we don’t know if calling condition.holds() again will yield the same result). Moreover, if we stop
the debugger at that line, we might not be able to conveniently see the result that causes the error, and,
again, even if we call that function again, we don’t know if that was the offending value.</p>
<p>A better alternative requires fewer lines of code and provides more useful information:</p>
<div class="highlight-python notranslate"><div class="highlight"><pre><span></span><span class="n">result</span> <span class="o">=</span> <span class="n">condition</span><span class="o">.</span><span class="n">holds</span><span class="p">()</span>
<span class="k">assert</span> <span class="n">result</span> <span class="o">&gt;</span> <span class="mi">0</span><span class="p">,</span> <span class="s2">&quot;Error with </span><span class="si">{0}</span><span class="s2">&quot;</span><span class="o">.</span><span class="n">format</span><span class="p">(</span><span class="n">result</span><span class="p">)</span>
</pre></div>
</div>
</div>
</div>


           </div>
           
          </div>
          <footer>
  

  <hr/>

  <div role="contentinfo">
    <p>
        &copy; Copyright 2019, Sergio Bugallo

    </p>
  </div>
  Built with <a href="http://sphinx-doc.org/">Sphinx</a> using a <a href="https://github.com/rtfd/sphinx_rtd_theme">theme</a> provided by <a href="https://readthedocs.org">Read the Docs</a>. 

</footer>

        </div>
      </div>

    </section>

  </div>
  


  <script type="text/javascript">
      jQuery(function () {
          SphinxRtdTheme.Navigation.enable(true);
      });
  </script>

  
  
    
   

</body>
</html>